/*
 * Copyright (c) 2025-2026 The Latte Project
 * SPDX-License-Identifier: MIT
 */
package org.lattejava.web;

import module org.lattejava.http;
import java.util.function.*;

/**
 * Parses the request body into a typed object.
 *
 * @param <T> The type of the parsed body.
 * @author Brian Pontarelli
 */
@FunctionalInterface
public interface BodySupplier<T> {
  /**
   * A simple adapter that takes a function that accepts the bytes of the request body and returns a typed object. This
   * is useful for handling JSON and other types where their is a function that does the deserialization, such as the
   * companion classes generated by the Latte <code>json</code> library.
   *
   * @param function The function that is applied to the request body.
   * @param <T>      The type.
   * @return The typed object (can really be anything).
   */
  static <T> BodySupplier<T> of(Function<byte[], T> function) {
    return (req, _) -> {
      try {
        var body = req.getBodyBytes();
        if (body == null || body.length == 0) {
          return null;
        }

        return function.apply(body);
      } catch (RuntimeException e) {
        throw new BadRequestException("The request body could not be parsed as JSON", e);
      }
    };
  }

  /**
   * Parses the request body into an object of type {@code T}.
   * <p>
   * Failure and emptiness are signalled differently:
   * <ul>
   *   <li>If the body cannot be parsed, the supplier should throw — typically a {@link BadRequestException} (or another
   *       {@link HTTPException}) so the framework renders the appropriate error response. The body handler is not
   *       invoked.</li>
   *   <li>If the body is empty but that is not an error (an empty body is valid for some routes), the supplier should
   *       return {@code null}. The framework then invokes the body handler with a {@code null} body, leaving the
   *       handler to decide whether a missing body is acceptable.</li>
   * </ul>
   *
   * @param req The request.
   * @param res The response.
   * @return The parsed body, or {@code null} to signal an empty (but valid) body.
   * @throws Exception if the body cannot be parsed; throw an {@link HTTPException} to control the response status.
   */
  T get(HTTPRequest req, HTTPResponse res) throws Exception;
}
