/*
 * Copyright (c) 2025-2026 The Latte Project
 * SPDX-License-Identifier: MIT
 */
package org.lattejava.web;

import module org.lattejava.http;
import java.util.function.*;

/**
 * Parses the request body into a typed object.
 *
 * @param <T> The type of the parsed body.
 * @author Brian Pontarelli
 */
@FunctionalInterface
public interface BodySupplier<T> {
  /**
   * Adapts a function from the raw body bytes to a typed object, such as a deserializer generated by the Latte
   * {@code json} library. An absent or empty body yields {@code null} without calling the function. A
   * {@link RuntimeException} thrown by the function is wrapped in a {@link BadRequestException}.
   *
   * @param <T>      The type of the parsed body.
   * @param function The function that parses the body bytes.
   * @return The supplier.
   */
  static <T> BodySupplier<T> of(Function<byte[], T> function) {
    return (req, _) -> {
      try {
        var body = req.getBodyBytes();
        if (body == null || body.length == 0) {
          return null;
        }

        return function.apply(body);
      } catch (RuntimeException e) {
        throw new BadRequestException("The request body could not be parsed as JSON", e);
      }
    };
  }

  /**
   * Parses the request body into an object of type {@code T}.
   * <p>
   * Failure and emptiness are signaled differently:
   * <ul>
   *   <li>If the body cannot be parsed, the supplier should throw — typically a {@link BadRequestException} (or another
   *       {@link HTTPException}) so the framework renders the appropriate error response. The body handler is not
   *       invoked.</li>
   *   <li>If the body is empty but that is not an error (an empty body is valid for some routes), the supplier should
   *       return {@code null}. The framework then invokes the body handler with a {@code null} body, leaving the
   *       handler to decide whether a missing body is acceptable.</li>
   * </ul>
   *
   * @param req The request.
   * @param res The response.
   * @return The parsed body, or {@code null} to signal an empty (but valid) body.
   * @throws Exception if the body cannot be parsed; throw an {@link HTTPException} to control the response status.
   */
  T get(HTTPRequest req, HTTPResponse res) throws Exception;
}
